### ISSUE TITLE
Extra space in the substitution variable values

### ISSUE THREAD

**Issue by dcerge** [sendgrid/smtpapi-csharp#74] opened 2018-06-29 12:18 UTC
#### Issue Summary

When sending emails to many recipients (in this case 100) and using substitution variables there will be several emails that have extra space in substitution variable values (in 3 emails of 100). This variable is used in URL so that why it is important not to have any not intended spaces.

#### Steps to Reproduce

I have attached:

* Program .cs file with the code from console .NET app which reproduces the bug. It sends 100 emails and extra space is in 25th, 50th, 76th emails - [program.txt](https://github.com/sendgrid/smtpapi-csharp/files/2149321/program.txt)
* Received email with extra space which is between "3128795c-2ef" and "3-4b2d-8873-ff99a8309b8f" - [emailexample.txt](https://github.com/sendgrid/smtpapi-csharp/files/2149323/emailexample.txt)
* SMTP log I captured with WireShark - [wiresharklog.txt](https://github.com/sendgrid/smtpapi-csharp/files/2149324/wiresharklog.txt)

#### Technical details:

* smtpapi-csharp Version: SendGrid.SmtpApi.1.3.3
* Platform ASP.NET
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment] 2018-07-02 16:40
Hello @dcerge,

This does not look like an SDK issue; however, I have some thoughts on how you might want to debug:

1. Log the values of the substitution or the request bodies before the emails are sent (this will help nail down if the issue is with your code on our servers.
2. Try the same test using our official [C# SDK](https://github.com/sendgrid/sendgrid-csharp). That might narrow the issue down between our SMTP and v3 Web API.

I hope that helps, thanks!

With Best Regards,

Elmer

**Comment by dcerge** [comment] 2018-07-02 17:29
Hi Elmer,

1. Here is JSON generated by header.JsonString():
[header-json.txt](https://github.com/sendgrid/smtpapi-csharp/files/2156140/header-json.txt)

Here is the email that has extra-space:
[exampleemail2.txt](https://github.com/sendgrid/smtpapi-csharp/files/2156147/exampleemail2.txt)

Extra space is between "283da7d6-d7b" and "1-4be6-b73a-baffbb7e1e1b". 

Note that this GUID does not have extra-space in the string generated by header.JsonString().

2. As for trying another your library I need some additional time. Do I understand correct that the library you recommend does not provide object-helpers to build send email request and I have to build JSON structure manually using string object? I tend to think so looking at the examples here https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md. If this is correct why does it lack functionality compared to the library I use now (SendGrid.SmtpApi)?

**Comment by dcerge** [comment] 2018-07-02 17:32
Hi Elmer,

1. Here is JSON generated by header.JsonString():
[header-json.txt](https://github.com/sendgrid/smtpapi-csharp/files/2156212/header-json.txt)
Here is the email that has extra-space:
[exampleemail2.txt](https://github.com/sendgrid/smtpapi-csharp/files/2156213/exampleemail2.txt)

Extra space is between "283da7d6-d7b" and "1-4be6-b73a-baffbb7e1e1b".

Note that this GUID does not have extra-space in the string generated by header.JsonString().

2. As for trying another your library I need some additional time. Do I understand correct that the library you recommend does not provide object-helpers to build send email request and I have to build JSON structure manually using string object? I tend to think so looking at the examples here https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md. If this is correct why does it lack functionality compared to the library I use now (SendGrid.SmtpApi)?

**Comment by thinkingserious** [comment] 2018-07-02 17:36
@dcerge,

1. If I'm reading this correctly, the generated JSON looks correct. So that leads me to believe it's a server side issue on our end. If that's the case, then I suggest you follow up with our support team as they are better equipped to help resolve such issues.

2. [We have helpers](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md) that will build the JSON for you.

Thanks!

**Comment by dcerge** [comment] 2018-07-02 17:56
@thinkingserious , thank you, I will contact support and also try another library to check if the issue appears there or not.

**Comment by dcerge** [comment] 2018-07-02 18:00
@thinkingserious , one more thing I forgot yo ask. Support said:

> Make sure that each line of content does not exceed 78 characters in length, nor that you exceed 998 continuous characters.

The library's header.JsonString() produces one long line that may actually cause the issue. Do you think if  the library format the string according to sendgrid's rules of line length then it would be not issue?

**Comment by thinkingserious** [comment] 2018-07-03 21:39
Hi @dcerge,

That's a great idea. I'll leave this issue open and our backlog.

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

With Best Regards,

Elmer

**Comment by eshanholtz** [comment] 2020-09-01 23:57
Closing as this is marked as a non-library issue.

**Closed by eshanholtz** 2020-09-01 23:57 UTC
Labels: difficulty: unknown or n/a, type: non-library issue
